app_port: 8000
migrates_folder: migrations
conf_validator:
  challenge_ttl: 30s
  challenge_max_allowed: 3
  challenge_difficulty: 2
conf_db:
  address: dbPostgres
  port: 5432
  user: aHAjeK
  pass: AOifjwelmc8dw
  db_name: sybill
  max_connections: 10